-- =====================================================================
-- V1 — Baseline schema (sinh tu pg_dump database chuan, 2026-07-18).
-- Tu day tro di, MOI thay doi schema phai la mot migration V{n}__*.sql moi;
-- KHONG sua file nay (Flyway kiem checksum, sua la loi khi khoi dong).
-- =====================================================================

CREATE TABLE public.classroom_sub_mentor (
    id bigint NOT NULL,
    classroom_subject_id bigint NOT NULL,
    sub_mentor_id bigint NOT NULL,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.classroom_sub_mentor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.classroom_sub_mentor_id_seq OWNED BY public.classroom_sub_mentor.id;

CREATE TABLE public.classroom_subject_students (
    classroom_subject_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    current_level integer,
    is_submentor boolean DEFAULT false NOT NULL
);

ALTER TABLE public.classroom_subject_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classroom_subject_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.classroom_subjects (
    classroom_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    lecturer_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    id_quiz_start bigint
);

ALTER TABLE public.classroom_subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classroom_subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.classrooms (
    is_deleted boolean,
    classroom_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(50) NOT NULL,
    class_name character varying(255) NOT NULL,
    description text,
    semester character varying(255),
    term character varying(20),
    academic_year integer
);

ALTER TABLE public.classrooms ALTER COLUMN classroom_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classrooms_classroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.files (
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    file_id bigint NOT NULL,
    material_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description text,
    file_name character varying(255),
    file_type character varying(255),
    file_url text NOT NULL,
    public_id character varying(255),
    resource_type character varying(20)
);

ALTER TABLE public.files ALTER COLUMN file_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.learning_nodes (
    display_order integer NOT NULL,
    is_deleted boolean,
    is_required boolean NOT NULL,
    created_at timestamp(6) without time zone,
    node_id bigint NOT NULL,
    path_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description text,
    node_status character varying(20) DEFAULT 'LOCKED'::character varying,
    node_type character varying(20),
    title character varying(255) NOT NULL,
    stage_order integer,
    level integer,
    test_kind character varying(20) DEFAULT 'NONE'::character varying,
    applies_levels character varying(20),
    gate_up_min numeric(5,2),
    gate_down_max numeric(5,2),
    placement_yeu_max numeric(5,2),
    placement_tb_max numeric(5,2),
    study_date date,
    slot_id bigint,
    deadline_at timestamp without time zone,
    session_started_at timestamp without time zone,
    session_ended_at timestamp without time zone,
    CONSTRAINT learning_nodes_node_status_check CHECK (((node_status)::text = ANY (ARRAY[('LOCKED'::character varying)::text, ('OPEN'::character varying)::text, ('HIDDEN'::character varying)::text]))),
    CONSTRAINT learning_nodes_node_type_check CHECK (((node_type)::text = ANY (ARRAY[('AT_HOME'::character varying)::text, ('ON_CLASS'::character varying)::text])))
);

ALTER TABLE public.learning_nodes ALTER COLUMN node_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_nodes_node_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.learning_paths (
    is_deleted boolean,
    classroom_subject_id bigint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    original_path_id bigint,
    path_id bigint NOT NULL,
    published_at timestamp(6) without time zone,
    published_by bigint,
    subject_id bigint,
    updated_at timestamp(6) without time zone,
    description text,
    path_name character varying(255) NOT NULL
);

ALTER TABLE public.learning_paths ALTER COLUMN path_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_path_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.node_edges (
    created_at timestamp(6) without time zone NOT NULL,
    edge_id bigint NOT NULL,
    from_node_id bigint NOT NULL,
    to_node_id bigint NOT NULL
);

ALTER TABLE public.node_edges ALTER COLUMN edge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_edges_edge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.node_exercises (
    exercise_id bigint NOT NULL,
    node_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    instructions text,
    allow_text boolean DEFAULT true,
    allow_file boolean DEFAULT true,
    order_index integer,
    is_deleted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.node_exercises_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.node_exercises_exercise_id_seq OWNED BY public.node_exercises.exercise_id;

CREATE TABLE public.node_materials (
    is_deleted boolean,
    order_index integer,
    required boolean,
    created_at timestamp(6) without time zone,
    material_id bigint NOT NULL,
    node_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    title character varying(255) NOT NULL
);

ALTER TABLE public.node_materials ALTER COLUMN material_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_materials_material_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.node_questions (
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    node_id bigint NOT NULL,
    question_id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    content text NOT NULL
);

ALTER TABLE public.node_questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.node_reviews (
    is_deleted boolean,
    rating integer,
    created_at timestamp(6) without time zone,
    node_id bigint NOT NULL,
    review_id bigint NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    content text,
    parent_review_id bigint,
    CONSTRAINT node_reviews_rating_check CHECK (((rating <= 5) AND (rating >= 1)))
);

ALTER TABLE public.node_reviews ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.node_reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.question_answers (
    answer_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    lecturer_id bigint NOT NULL,
    question_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    content text NOT NULL,
    is_deleted boolean DEFAULT false
);

ALTER TABLE public.question_answers ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.quiz_score_bands (
    band_id bigint NOT NULL,
    test_id bigint NOT NULL,
    min_score numeric(5,2) NOT NULL,
    max_score numeric(5,2) NOT NULL,
    target_level integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.quiz_score_bands_band_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.quiz_score_bands_band_id_seq OWNED BY public.quiz_score_bands.band_id;

CREATE TABLE public.retake_requests (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    classroom_subject_id bigint NOT NULL,
    test_id bigint NOT NULL,
    status character varying(50) NOT NULL,
    request_reason text,
    reject_reason text,
    requested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    resolved_at timestamp without time zone,
    resolved_by bigint
);

CREATE SEQUENCE public.retake_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.retake_requests_id_seq OWNED BY public.retake_requests.id;

CREATE TABLE public.roles (
    created_at timestamp(6) without time zone,
    role_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    role_name character varying(20),
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('TEACHER'::character varying)::text, ('STUDENT'::character varying)::text, ('SUB_MENTOR'::character varying)::text, ('USER'::character varying)::text])))
);

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.semesters (
    semester_id bigint NOT NULL,
    term character varying(20) NOT NULL,
    academic_year integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.semesters ALTER COLUMN semester_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semesters_semester_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.slots (
    slot_id bigint NOT NULL,
    slot_name character varying(50) NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.slots_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.slots_slot_id_seq OWNED BY public.slots.slot_id;

CREATE TABLE public.student_learning_routes (
    assigned_at timestamp(6) without time zone NOT NULL,
    assigned_by bigint,
    edge_id bigint NOT NULL,
    id bigint NOT NULL,
    student_id bigint NOT NULL
);

ALTER TABLE public.student_learning_routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_learning_routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_level_history (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    classroom_subject_id bigint NOT NULL,
    old_level integer,
    new_level integer NOT NULL,
    reason character varying(50) NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.student_level_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.student_level_history_id_seq OWNED BY public.student_level_history.id;

CREATE TABLE public.student_material_progress (
    progress_id bigint NOT NULL,
    classroom_subject_student_id bigint NOT NULL,
    material_id bigint NOT NULL,
    completed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.student_material_progress_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.student_material_progress_progress_id_seq OWNED BY public.student_material_progress.progress_id;

CREATE TABLE public.student_node_progress (
    order_index integer NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    node_id bigint NOT NULL,
    path_id bigint NOT NULL,
    progress_id bigint NOT NULL,
    unlocked_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    classroom_subject_student_id bigint NOT NULL,
    completed_late boolean DEFAULT false
);

ALTER TABLE public.student_node_progress ALTER COLUMN progress_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_node_progress_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_selected_answers (
    answer_id bigint NOT NULL,
    response_id bigint NOT NULL
);

CREATE TABLE public.student_test_attempts (
    score numeric(5,2),
    attempt_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    started_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone,
    test_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(20) DEFAULT 'SUBMITTED'::character varying,
    tab_out_count integer DEFAULT 0
);

ALTER TABLE public.student_test_attempts ALTER COLUMN attempt_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_test_attempts_attempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.student_test_responses (
    is_correct boolean,
    attempt_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    question_id bigint NOT NULL,
    response_id bigint NOT NULL,
    selected_answer_id bigint,
    updated_at timestamp(6) without time zone,
    response_text text
);

ALTER TABLE public.student_test_responses ALTER COLUMN response_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_test_responses_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sub_mentor_student_assignment (
    id bigint NOT NULL,
    sub_mentor_css_id bigint NOT NULL,
    student_css_id bigint NOT NULL,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sub_mentor_student_assignment_check CHECK ((sub_mentor_css_id <> student_css_id))
);

CREATE SEQUENCE public.sub_mentor_student_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.sub_mentor_student_assignment_id_seq OWNED BY public.sub_mentor_student_assignment.id;

CREATE TABLE public.subjects (
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    created_by bigint,
    subject_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    status character varying(50) NOT NULL,
    description text,
    subject_code character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL,
    learningpath_length integer
);

ALTER TABLE public.subjects ALTER COLUMN subject_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.submissions (
    grade numeric(5,2),
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    graded_at timestamp(6) without time zone,
    graded_by bigint,
    node_id bigint NOT NULL,
    student_id bigint NOT NULL,
    submission_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content text,
    feedback text,
    file_url text,
    submission_status character varying(20) DEFAULT 'PENDING'::character varying,
    title character varying(255),
    exercise_id bigint,
    CONSTRAINT submissions_submission_status_check CHECK (((submission_status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('SUBMITTED'::character varying)::text, ('LATE'::character varying)::text, ('GRADED'::character varying)::text])))
);

ALTER TABLE public.submissions ALTER COLUMN submission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.submissions_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.support_tickets (
    ticket_id bigint NOT NULL,
    classroom_subject_student_id bigint NOT NULL,
    message_student text NOT NULL,
    message_response text,
    status character varying(20) DEFAULT 'NONE'::character varying NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.support_tickets_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.support_tickets_ticket_id_seq OWNED BY public.support_tickets.ticket_id;

CREATE TABLE public.test_answers (
    is_correct boolean,
    answer_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    question_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    answer_content text NOT NULL
);

ALTER TABLE public.test_answers ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_answers_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.test_assignment_students (
    id bigint NOT NULL,
    assignment_id bigint NOT NULL,
    classroom_subject_student_id bigint NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    attempt_id bigint,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.test_assignment_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.test_assignment_students_id_seq OWNED BY public.test_assignment_students.id;

CREATE TABLE public.test_assignments (
    assignment_id bigint NOT NULL,
    test_id bigint NOT NULL,
    node_id bigint NOT NULL,
    classroom_subject_id bigint NOT NULL,
    assigned_by bigint NOT NULL,
    status character varying(20) DEFAULT 'OPEN'::character varying NOT NULL,
    close_at timestamp without time zone,
    is_deleted boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE public.test_assignments_assignment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.test_assignments_assignment_id_seq OWNED BY public.test_assignments.assignment_id;

CREATE TABLE public.test_questions (
    score numeric(5,2),
    created_at timestamp(6) without time zone,
    question_id bigint NOT NULL,
    test_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    question_content text NOT NULL,
    question_type character varying(255) NOT NULL,
    CONSTRAINT test_questions_question_type_check CHECK (((question_type)::text = ANY (ARRAY[('MULTIPLE_CHOICE'::character varying)::text, ('MULTIPLE_SELECT'::character varying)::text, ('TRUE_FALSE'::character varying)::text, ('SHORT_ANSWER'::character varying)::text, ('ESSAY'::character varying)::text])))
);

ALTER TABLE public.test_questions ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tests (
    duration_minutes integer,
    is_deleted boolean,
    order_index integer,
    passing_percentage numeric(5,2),
    created_at timestamp(6) without time zone,
    node_id bigint,
    test_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description text,
    title character varying(255) NOT NULL,
    release_ends_at timestamp without time zone,
    released_at timestamp without time zone,
    test_kind character varying(20) DEFAULT 'NORMAL'::character varying NOT NULL
);

ALTER TABLE public.tests ALTER COLUMN test_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tokens (
    is_revoked boolean,
    created_at timestamp(6) without time zone,
    expired_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    access_token text,
    refresh_token text,
    reset_token text
);

ALTER TABLE public.tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_account (
    bod date,
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    avatar_url text,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    gender character varying(10),
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255),
    status character varying(20) DEFAULT 'ACTIVE'::character varying,
    CONSTRAINT user_account_gender_check CHECK (((gender)::text = ANY (ARRAY[('MALE'::character varying)::text, ('FEMALE'::character varying)::text, ('OTHER'::character varying)::text]))),
    CONSTRAINT user_account_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('NONE'::character varying)::text])))
);

ALTER TABLE public.user_account ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_account_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_role (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    user_role_id bigint NOT NULL
);

ALTER TABLE public.user_role ALTER COLUMN user_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_role_user_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.videos (
    duration_seconds integer,
    is_deleted boolean,
    created_at timestamp(6) without time zone,
    material_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    video_id bigint NOT NULL,
    description text,
    title character varying(255),
    video_url text NOT NULL
);

ALTER TABLE public.videos ALTER COLUMN video_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videos_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.classroom_sub_mentor ALTER COLUMN id SET DEFAULT nextval('public.classroom_sub_mentor_id_seq'::regclass);

ALTER TABLE ONLY public.node_exercises ALTER COLUMN exercise_id SET DEFAULT nextval('public.node_exercises_exercise_id_seq'::regclass);

ALTER TABLE ONLY public.quiz_score_bands ALTER COLUMN band_id SET DEFAULT nextval('public.quiz_score_bands_band_id_seq'::regclass);

ALTER TABLE ONLY public.retake_requests ALTER COLUMN id SET DEFAULT nextval('public.retake_requests_id_seq'::regclass);

ALTER TABLE ONLY public.slots ALTER COLUMN slot_id SET DEFAULT nextval('public.slots_slot_id_seq'::regclass);

ALTER TABLE ONLY public.student_level_history ALTER COLUMN id SET DEFAULT nextval('public.student_level_history_id_seq'::regclass);

ALTER TABLE ONLY public.student_material_progress ALTER COLUMN progress_id SET DEFAULT nextval('public.student_material_progress_progress_id_seq'::regclass);

ALTER TABLE ONLY public.sub_mentor_student_assignment ALTER COLUMN id SET DEFAULT nextval('public.sub_mentor_student_assignment_id_seq'::regclass);

ALTER TABLE ONLY public.support_tickets ALTER COLUMN ticket_id SET DEFAULT nextval('public.support_tickets_ticket_id_seq'::regclass);

ALTER TABLE ONLY public.test_assignment_students ALTER COLUMN id SET DEFAULT nextval('public.test_assignment_students_id_seq'::regclass);

ALTER TABLE ONLY public.test_assignments ALTER COLUMN assignment_id SET DEFAULT nextval('public.test_assignments_assignment_id_seq'::regclass);

ALTER TABLE ONLY public.classroom_sub_mentor
    ADD CONSTRAINT classroom_sub_mentor_classroom_subject_id_sub_mentor_id_key UNIQUE (classroom_subject_id, sub_mentor_id);

ALTER TABLE ONLY public.classroom_sub_mentor
    ADD CONSTRAINT classroom_sub_mentor_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.classroom_subject_students
    ADD CONSTRAINT classroom_subject_students_classroom_subject_id_student_id_key UNIQUE (classroom_subject_id, student_id);

ALTER TABLE ONLY public.classroom_subject_students
    ADD CONSTRAINT classroom_subject_students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT classroom_subjects_classroom_id_subject_id_key UNIQUE (classroom_id, subject_id);

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT classroom_subjects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.classrooms
    ADD CONSTRAINT classrooms_pkey PRIMARY KEY (classroom_id);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (file_id);

ALTER TABLE ONLY public.learning_nodes
    ADD CONSTRAINT learning_nodes_pkey PRIMARY KEY (node_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT learning_paths_pkey PRIMARY KEY (path_id);

ALTER TABLE ONLY public.node_edges
    ADD CONSTRAINT node_edges_from_node_id_to_node_id_key UNIQUE (from_node_id, to_node_id);

ALTER TABLE ONLY public.node_edges
    ADD CONSTRAINT node_edges_pkey PRIMARY KEY (edge_id);

ALTER TABLE ONLY public.node_exercises
    ADD CONSTRAINT node_exercises_pkey PRIMARY KEY (exercise_id);

ALTER TABLE ONLY public.node_materials
    ADD CONSTRAINT node_materials_pkey PRIMARY KEY (material_id);

ALTER TABLE ONLY public.node_questions
    ADD CONSTRAINT node_questions_pkey PRIMARY KEY (question_id);

ALTER TABLE ONLY public.node_reviews
    ADD CONSTRAINT node_reviews_pkey PRIMARY KEY (review_id);

ALTER TABLE ONLY public.question_answers
    ADD CONSTRAINT question_answers_pkey PRIMARY KEY (answer_id);

ALTER TABLE ONLY public.quiz_score_bands
    ADD CONSTRAINT quiz_score_bands_pkey PRIMARY KEY (band_id);

ALTER TABLE ONLY public.retake_requests
    ADD CONSTRAINT retake_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);

ALTER TABLE ONLY public.semesters
    ADD CONSTRAINT semesters_pkey PRIMARY KEY (semester_id);

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT slots_pkey PRIMARY KEY (slot_id);

ALTER TABLE ONLY public.slots
    ADD CONSTRAINT slots_slot_name_key UNIQUE (slot_name);

ALTER TABLE ONLY public.student_learning_routes
    ADD CONSTRAINT student_learning_routes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_level_history
    ADD CONSTRAINT student_level_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_material_progress
    ADD CONSTRAINT student_material_progress_classroom_subject_student_id_mate_key UNIQUE (classroom_subject_student_id, material_id);

ALTER TABLE ONLY public.student_material_progress
    ADD CONSTRAINT student_material_progress_pkey PRIMARY KEY (progress_id);

ALTER TABLE ONLY public.student_node_progress
    ADD CONSTRAINT student_node_progress_pkey PRIMARY KEY (progress_id);

ALTER TABLE ONLY public.student_test_attempts
    ADD CONSTRAINT student_test_attempts_pkey PRIMARY KEY (attempt_id);

ALTER TABLE ONLY public.student_test_responses
    ADD CONSTRAINT student_test_responses_attempt_id_question_id_key UNIQUE (attempt_id, question_id);

ALTER TABLE ONLY public.student_test_responses
    ADD CONSTRAINT student_test_responses_pkey PRIMARY KEY (response_id);

ALTER TABLE ONLY public.sub_mentor_student_assignment
    ADD CONSTRAINT sub_mentor_student_assignment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sub_mentor_student_assignment
    ADD CONSTRAINT sub_mentor_student_assignment_sub_mentor_css_id_student_css_key UNIQUE (sub_mentor_css_id, student_css_id);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (subject_id);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_subject_code_key UNIQUE (subject_code);

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (submission_id);

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_pkey PRIMARY KEY (ticket_id);

ALTER TABLE ONLY public.test_answers
    ADD CONSTRAINT test_answers_pkey PRIMARY KEY (answer_id);

ALTER TABLE ONLY public.test_assignment_students
    ADD CONSTRAINT test_assignment_students_assignment_id_classroom_subject_st_key UNIQUE (assignment_id, classroom_subject_student_id);

ALTER TABLE ONLY public.test_assignment_students
    ADD CONSTRAINT test_assignment_students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.test_assignments
    ADD CONSTRAINT test_assignments_pkey PRIMARY KEY (assignment_id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT test_questions_pkey PRIMARY KEY (question_id);

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (test_id);

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.student_node_progress
    ADD CONSTRAINT uq_snp_css_node_path UNIQUE (classroom_subject_student_id, node_id, path_id);

ALTER TABLE ONLY public.semesters
    ADD CONSTRAINT uq_term_academic_year UNIQUE (term, academic_year);

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT user_account_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (user_role_id);

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (video_id);

CREATE INDEX idx_csm_subject_mentor ON public.classroom_sub_mentor USING btree (classroom_subject_id, sub_mentor_id);

CREATE INDEX idx_node_edges_from ON public.node_edges USING btree (from_node_id);

CREATE INDEX idx_node_edges_to ON public.node_edges USING btree (to_node_id);

CREATE INDEX idx_quiz_score_bands_test ON public.quiz_score_bands USING btree (test_id);

CREATE INDEX idx_slh_student_cs ON public.student_level_history USING btree (student_id, classroom_subject_id);

CREATE INDEX idx_snp_path_status ON public.student_node_progress USING btree (path_id, status);

CREATE INDEX idx_test_assignment_students_css ON public.test_assignment_students USING btree (classroom_subject_student_id);

CREATE INDEX idx_test_assignments_node_status ON public.test_assignments USING btree (node_id, status);

CREATE UNIQUE INDEX idx_user_account_active_email ON public.user_account USING btree (email) WHERE (is_deleted = false);

CREATE UNIQUE INDEX uniq_active_classroom_subject_path ON public.learning_paths USING btree (classroom_subject_id) WHERE ((classroom_subject_id IS NOT NULL) AND (is_deleted = false));

CREATE UNIQUE INDEX uq_node_reviews_root ON public.node_reviews USING btree (student_id, node_id) WHERE ((parent_review_id IS NULL) AND (rating IS NOT NULL));

ALTER TABLE ONLY public.classroom_sub_mentor
    ADD CONSTRAINT classroom_sub_mentor_classroom_subject_id_fkey FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.classroom_sub_mentor
    ADD CONSTRAINT classroom_sub_mentor_sub_mentor_id_fkey FOREIGN KEY (sub_mentor_id) REFERENCES public.user_account(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT classroom_subjects_id_quiz_start_fkey FOREIGN KEY (id_quiz_start) REFERENCES public.tests(test_id) ON DELETE SET NULL;

ALTER TABLE ONLY public.student_test_responses
    ADD CONSTRAINT fk1frp3du4bdyylhunj3yw83fqd FOREIGN KEY (attempt_id) REFERENCES public.student_test_attempts(attempt_id);

ALTER TABLE ONLY public.node_edges
    ADD CONSTRAINT fk38dlqe1mkcinh9v49lcpcsgdu FOREIGN KEY (to_node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.classroom_subject_students
    ADD CONSTRAINT fk3elp8jmv5j0ojmo5fcni3bxxl FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id);

ALTER TABLE ONLY public.student_node_progress
    ADD CONSTRAINT fk3l1ovvkpsqnkvy58abtu88151 FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.student_test_responses
    ADD CONSTRAINT fk4xvqp0p7ru5kacsgl7t1aq0pp FOREIGN KEY (question_id) REFERENCES public.test_questions(question_id);

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk5rtt6v2nxy243419ybpvehejg FOREIGN KEY (graded_by) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_selected_answers
    ADD CONSTRAINT fk60msl3jxkgifnj1h0v1lcqugx FOREIGN KEY (response_id) REFERENCES public.student_test_responses(response_id);

ALTER TABLE ONLY public.question_answers
    ADD CONSTRAINT fk6vjjvas6irx1jrf7tbxn7m3c4 FOREIGN KEY (lecturer_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.question_answers
    ADD CONSTRAINT fk7lm7c49s6gbbem35c0mjisyo4 FOREIGN KEY (question_id) REFERENCES public.node_questions(question_id);

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fk7ojmv1m1vrxfl3kvt5bi5ur73 FOREIGN KEY (user_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.node_questions
    ADD CONSTRAINT fk7tkhoo53hoapbh9yxycmcveyk FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.test_answers
    ADD CONSTRAINT fk947jmj9c58ke35phe4qqetbtm FOREIGN KEY (question_id) REFERENCES public.test_questions(question_id);

ALTER TABLE ONLY public.node_edges
    ADD CONSTRAINT fk94arph4wc0ctbplanh3bk6j2f FOREIGN KEY (from_node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fk99264v6gk6oc6dvhq4a6hrnm FOREIGN KEY (created_by) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_node_progress
    ADD CONSTRAINT fk_snp_css FOREIGN KEY (classroom_subject_student_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT fkaf0nxewcn5v7m6b2jjtx3puh9 FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);

ALTER TABLE ONLY public.node_reviews
    ADD CONSTRAINT fkanwjrwoc69g35b62ofdh1lh0c FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.learning_nodes
    ADD CONSTRAINT fkauh0f0klox9rpp4keiqnsmhrp FOREIGN KEY (path_id) REFERENCES public.learning_paths(path_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkbr7opd8p7t6yo1t9qyd06gxdw FOREIGN KEY (published_by) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkdvh0ajieoy4llvs34ka9m8o2p FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT fket15l0n9cpt9t6aq6r4xh0xn8 FOREIGN KEY (classroom_id) REFERENCES public.classrooms(classroom_id);

ALTER TABLE ONLY public.student_test_attempts
    ADD CONSTRAINT fkfmrd891bbu0l5ikk8ipxmthf9 FOREIGN KEY (test_id) REFERENCES public.tests(test_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkhhecq4xw7dufwa5jwgphfggxd FOREIGN KEY (original_path_id) REFERENCES public.learning_paths(path_id);

ALTER TABLE ONLY public.files
    ADD CONSTRAINT fkjj0erkogigiyjtq0flxqreho5 FOREIGN KEY (material_id) REFERENCES public.node_materials(material_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkk9gk0bsrsxhkuc9vencbaja3s FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);

ALTER TABLE ONLY public.learning_paths
    ADD CONSTRAINT fkku4n3xs0e0mfnyj9y8rvrac6c FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id);

ALTER TABLE ONLY public.student_selected_answers
    ADD CONSTRAINT fklfbm0jwa0m7ylur5o6xosjkad FOREIGN KEY (answer_id) REFERENCES public.test_answers(answer_id);

ALTER TABLE ONLY public.node_materials
    ADD CONSTRAINT fkm7n0l1lggdtkdsqnmqh250jo3 FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.student_test_responses
    ADD CONSTRAINT fkmeupvmw41x06ml335bi15k70b FOREIGN KEY (selected_answer_id) REFERENCES public.test_answers(answer_id);

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT fkmo2f0l9x3d0h9o6daufol1qsl FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fkna0vv2uhlhs1g6ffr9q9wtl6w FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_learning_routes
    ADD CONSTRAINT fknj17q9ixt1didx4h7joop9f5j FOREIGN KEY (assigned_by) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_learning_routes
    ADD CONSTRAINT fkomxk04ilq91kj5eaibdabbpba FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.node_questions
    ADD CONSTRAINT fkq11yb3c1yv3ecc8wdur1qw6yy FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.test_questions
    ADD CONSTRAINT fkq1jpgjcbjbulxvhdkctcxhg12 FOREIGN KEY (test_id) REFERENCES public.tests(test_id);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT fkq5b3dwjmco8jt8lrksv9maaia FOREIGN KEY (created_by) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_node_progress
    ADD CONSTRAINT fkq5cuf8g9xtwxc5m6vjm8o113t FOREIGN KEY (path_id) REFERENCES public.learning_paths(path_id);

ALTER TABLE ONLY public.classroom_subject_students
    ADD CONSTRAINT fkqidpy2pdl5b5slw0h1mkn64f2 FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_test_attempts
    ADD CONSTRAINT fkqyjxc8ty67h15mqreqfm07ro4 FOREIGN KEY (student_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.classroom_subjects
    ADD CONSTRAINT fkr7m5qr2dknqgv79rdo2xulfj0 FOREIGN KEY (lecturer_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.student_learning_routes
    ADD CONSTRAINT fkrh680wxeudoqn35agdyiha73k FOREIGN KEY (edge_id) REFERENCES public.node_edges(edge_id);

ALTER TABLE ONLY public.node_reviews
    ADD CONSTRAINT fks5hljmqujoylkb9pj68odtct4 FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id);

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT fkt3ve2qsy4ikkfe7epgs38tnm9 FOREIGN KEY (user_id) REFERENCES public.user_account(user_id);

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT fkt3xxqv7uebmap112k049tlknl FOREIGN KEY (material_id) REFERENCES public.node_materials(material_id);

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id) REFERENCES public.roles(role_id);

ALTER TABLE ONLY public.learning_nodes
    ADD CONSTRAINT learning_nodes_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES public.slots(slot_id) ON DELETE SET NULL;

ALTER TABLE ONLY public.node_exercises
    ADD CONSTRAINT node_exercises_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.node_reviews
    ADD CONSTRAINT node_reviews_parent_review_id_fkey FOREIGN KEY (parent_review_id) REFERENCES public.node_reviews(review_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.quiz_score_bands
    ADD CONSTRAINT quiz_score_bands_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.tests(test_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.retake_requests
    ADD CONSTRAINT retake_requests_classroom_subject_id_fkey FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.retake_requests
    ADD CONSTRAINT retake_requests_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.user_account(user_id) ON DELETE SET NULL;

ALTER TABLE ONLY public.retake_requests
    ADD CONSTRAINT retake_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_account(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.retake_requests
    ADD CONSTRAINT retake_requests_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.tests(test_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.student_level_history
    ADD CONSTRAINT student_level_history_classroom_subject_id_fkey FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.student_level_history
    ADD CONSTRAINT student_level_history_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.user_account(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.student_material_progress
    ADD CONSTRAINT student_material_progress_classroom_subject_student_id_fkey FOREIGN KEY (classroom_subject_student_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.student_material_progress
    ADD CONSTRAINT student_material_progress_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.node_materials(material_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sub_mentor_student_assignment
    ADD CONSTRAINT sub_mentor_student_assignment_student_css_id_fkey FOREIGN KEY (student_css_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.sub_mentor_student_assignment
    ADD CONSTRAINT sub_mentor_student_assignment_sub_mentor_css_id_fkey FOREIGN KEY (sub_mentor_css_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.node_exercises(exercise_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_classroom_subject_student_id_fkey FOREIGN KEY (classroom_subject_student_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignment_students
    ADD CONSTRAINT test_assignment_students_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.test_assignments(assignment_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignment_students
    ADD CONSTRAINT test_assignment_students_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES public.student_test_attempts(attempt_id) ON DELETE SET NULL;

ALTER TABLE ONLY public.test_assignment_students
    ADD CONSTRAINT test_assignment_students_classroom_subject_student_id_fkey FOREIGN KEY (classroom_subject_student_id) REFERENCES public.classroom_subject_students(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignments
    ADD CONSTRAINT test_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.user_account(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignments
    ADD CONSTRAINT test_assignments_classroom_subject_id_fkey FOREIGN KEY (classroom_subject_id) REFERENCES public.classroom_subjects(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignments
    ADD CONSTRAINT test_assignments_node_id_fkey FOREIGN KEY (node_id) REFERENCES public.learning_nodes(node_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.test_assignments
    ADD CONSTRAINT test_assignments_test_id_fkey FOREIGN KEY (test_id) REFERENCES public.tests(test_id) ON DELETE CASCADE;

